### ISSUE TITLE
`tabs` 风格与官方 `code-group` 不相符

### ISSUE THREAD

**Issue by Suomm** [sapphi-red/vitepress-plugins#45]
`tabs` style does not match the official `code-group`.

**Comment by Suomm** [comment]
![image](https://github.com/sapphi-red/vitepress-plugins/assets/27558987/e09bf78e-bb4d-4795-9225-f764d7cfea36)

**Comment by Suomm** [comment]
tabs スタイルは公式 code-group と合わない.

**Comment by sapphi-red** [comment]
It's because these plugin existed before the code-group feature was added.
PRs to change using the code-group feature for plugin-detype and plugin-npm-commands are welcome.

**Comment by sapphi-red** [comment]
Duplicate of https://github.com/sapphi-red/vitepress-plugins/issues/12
